Add babel transporter plugin
direct-adv-interfaces/direct-dev pull request #18
Opened 2017-04-10 14:14 UTC by heliarian

2017-04-10 15:31 UTC, dima117 requested changes

2017-04-10 15:31 UTC, dima117 commented on TECHS.md
> +            dev.transporterPlugins.babel({ filter }),  //применяем babel
зачем тут фильтр?

2017-04-10 15:31 UTC, dima117 commented on lib/techs/transporter-plugins/babel.js
> +                    { filenameRelative : file.path },
внутри `file.path` точно относительный путь?

2017-04-10 15:31 UTC, dima117 commented on TECHS.md
> +            dev.transporterPlugins.babel({ filter }),  //применяем babel
Поговорили голосом. Нужно добавить в BlockFilter возможность фильтрации по технологии + исправить пример в md, чтобы передавались разные фильтры для `coverage` и `babel`.

2017-04-10 15:31 UTC, dima117 commented on TECHS.md
> +            dev.transporterPlugins.babel({ filter }),  //применяем babel
и еще нужно добавить `babel` в список [чуть выше](https://github.com/direct-adv-interfaces/direct-dev/pull/18/files#diff-a207aacc162aa6bf6fa4d99a022fc5eeL197) в md.

2017-04-10 15:31 UTC, dima117 commented on lib/index.js
> +        babel: require('./techs/transporter-plugins/wrap')
неправильный путь

2017-04-10 15:31 UTC, dima117 commented on package.json
> +    "babel": "^6.23.0",
предлагаю указать зависимость без `^`

2017-04-10 15:31 UTC, dima117 commented on package.json
> +    "babel": "^6.23.0",
Также нужно проверить сборку тестового проекта на старой ноде (подключать папку `es5lib `).

2017-04-11 15:11 UTC, heliarian commented on lib/techs/transporter-plugins/babel.js
> +                    { filenameRelative : file.path },
Ты прав, перепутала

2017-04-12 09:59 UTC, dima117 requested changes

2017-04-12 09:59 UTC, dima117 commented on lib/utils/block-filter.js
> +        let sourceSuffixes = Array.isArray(this.data.sourceSuffixes) ?
лучше так:
```js
let sourceSuffixes = [].concat(this.data.sourceSuffixes || []);
```

2017-04-12 09:59 UTC, dima117 commented on lib/utils/block-filter.js
> +        let sourceRegex = `\.(${sourceSuffixes.join('|').replace('.', '\.')})$`;
Можешь переименовать в techs и сравнивать не всё имя файла, а только технологию (то, что после первой точки)? Сейчас получается, что, если указать фильтр по `'.js'`, то в него попадут `'.utils.js'`, `'.vm.js'` и т.п. 😞

2017-04-12 09:59 UTC, dima117 commented on lib/utils/block-filter.js
> +        let sourceRegex = `\.(${sourceSuffixes.join('|').replace('.', '\.')})$`;
наверно, я бы на твоем месте сделал как-то так
```js
let techs = [].concat(this.data.sourceSuffixes || []);
let hash = lodash.keyBy(techs)
let tech = path.basename(filePath).split('.').slice(1).join('.');

return !!hash[tech];
```

Еще внизу есть `path.basename(filePath).split('.')` для получения названия блока без технологии - можно вынести в переменную.

2017-04-12 10:26 UTC, dima117 requested changes

2017-04-12 10:26 UTC, dima117 commented on lib/utils/block-filter.js
> +    let baseName = path.basename(filePath).split('.')[0];
в чем смысл переноса этой строки наверх?
предлагаю убрать отсюда `[0]`

```js
let parts = path.basename(filePath).split('.');
```

в строке 27 написать 

```js
let tech = parts.slice(1).join('.');
```

в строке 34 написать 

```js
let baseName = parts[0];
```

2017-04-12 10:31 UTC, dima117 approved these changes

2017-04-12 10:32 UTC, merged